### ISSUE TITLE
IsolatedTestRunnerAdapter: Can not load "webpack" preprocessor - cannot load webpack options if any plugin was added

### ISSUE THREAD

**Issue by unlight** [stryker-mutator/stryker-karma-runner#22]
Error Can not load "webpack" 
`arguments[i].apply is not a function`
Can't load webpack options from karmaConfig from stryker config.
Error happens only if any plugin is added.

How to reproduce:
```
git clone https://github.com/unlight/angular-webpack-seed
cd angular-webpack-seed
git checkout bug-1
npm i
npm run stryker -q
```
Expected behaviour:
```
No errors
```
Actual:
```
[2017-04-20 13:12:34.248] [TRACE] IsolatedTestRunnerAdapter - 20 04 2017 13:12:34.241:
ERROR [preprocess]: Can not load "webpack"!
  TypeError: arguments[i].apply is not a function
    at Compiler.apply (d:\Dev\angular-webpack-seed\node_modules\tapable\lib\Tapable.js:310:16)
    at webpack (d:\Dev\angular-webpack-seed\node_modules\webpack\lib\webpack.js:32:19)
    at new Plugin (d:\Dev\angular-webpack-seed\node_modules\karma-webpack\lib\karma-webpack.js:69:15)
    at invoke (d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:59:20)
    at get (d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:48:43)
    at d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
    at Array.invoke (d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:70:31)
    at Injector.get (d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (d:\Dev\angular-webpack-seed\node_modules\karma\lib\preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (d:\Dev\angular-webpack-seed\node_modules\karma\lib\preprocessor.js:74:20)
    at Array.invoke (d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:75:15)
    at get (d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:48:43)
    at d:\Dev\angular-webpack-seed\node_modules\di\lib\injector.js:71:14
```
Env:
windows 10
node v7.9.0
part of stryker config:
```
        karmaConfig: {
            preprocessors: {
                '**/spec.module.js': ['webpack'],
            },
            browsers: ['Nightmare'],
            webpack: {
                module: {
                    exprContextCritical: false,
                    rules: [
                        {
                            test: /\.component\.html$/,
                            use: [
                                { loader: 'raw-loader' }
                            ]
                        },
                        {
                            test: /\.component\.scss$/,
                            use: [
                                { loader: 'raw-loader' },
                                { loader: 'sass-loader' },
                            ]
                        },
                        {
                            test: /\.component\.[tj]s$/,
                            use: [
                                { loader: 'angular2-template-loader' }
                            ]
                        }
                    ]
                },
                plugins: [
                    new webpack.DefinePlugin({
                        'process.env.NODE_ENV': JSON.stringify('development')
                    }),
                    // new webpack.DllReferencePlugin({
                    //     context: context,
                    //     manifest: require(libs)
                    // })
                ]
            }
        },
```

**Comment by unlight** [comment]
#22
